### ISSUE TITLE
Monochromatic (themed) icon support

### ISSUE THREAD

**Issue by rodrigoswz** [Catfriend1/syncthing-android#1006]
### Description of the issue

Please, any chance to add a themed icon (Android 13+ feature)?

Google's official guidelines:
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#design-adaptive-icons

**Comment by Catfriend1** [comment]
Sure, you can make a PR :)

**Comment by vada-pav** [comment]
@Catfriend1 is this implemented?
I am on LineageOS 20 and I don’t see the themed icon.

**Comment by kgorol** [comment]
![Screenshot_20231116_105351_One UI Home](https://github.com/Catfriend1/syncthing-android/assets/34159482/55135a6f-2bde-494f-be03-05767ab8530e)
Icon is broken after latest update. Is this related @Catfriend1 ?

**Comment by Catfriend1** [comment]
It could also be the sdk Level bump to 34 .
Displays fine on my Android 13.

**Comment by vada-pav** [comment]
Same issue for me. I am on LineageOS 20.
![Screenshot_20231116-192328_Trebuchet](https://github.com/Catfriend1/syncthing-android/assets/59252456/ca1361a8-d972-43c2-8309-c99301542cd7)

**Comment by Catfriend1** [comment]
So I think this is valid. But not worth my time if Google breaks icons...

**Comment by MailYouLater** [comment]
I'm seeing a distorted 'themed icon' on Android 14 too.  It looks pretty bad to me on my phone, so I checked the upstream app, and its icon looks better.

Here's what the icons look like on my phone.  The top icons are what show by default, the bottom icons show when 'Themed icons" is enabled; the left icons are for Syncthing-Fork, the right icons are for the upstream Syncthing app.
![Comparison of icons for Syncthing-Fork and Syncthing with their 'normal' icon and their 'monochrome' variants](https://github.com/Catfriend1/syncthing-android/assets/1279475/8e931d74-7186-4a5d-9702-bce2cd4f557a)

The upstream repo appears to have made this fix in https://github.com/syncthing/syncthing-android/commit/e46ec1cfee2f670028a5d7676ac5de93156ba3bf.  It's a big commit, but after a quick glance it seems that only a small amount of it would be needed to just fix the icon if you don't want to do the full 'Migration to Material Design 3' that the commit message describes.  The pertinent changes seem to be the introduction of a vector icon file ([/app/src/main/res/drawable/ic_monochrome.xml](https://github.com/syncthing/syncthing-android/blob/e46ec1cfee2f670028a5d7676ac5de93156ba3bf/app/src/main/res/drawable/ic_monochrome.xml)) and a few lines that reference it.  The apps both use the same non-themed icon, as well as the MPL 2.0 license, so... are you allowed to just cherrypick the relevant portions of that commit to fix this?

**Comment by Catfriend1** [comment]
I think we could merge the relevant part. Which lines of the huge diff are that?

**Comment by MailYouLater** [comment]
> I did not notice the render problem on the Android 14 emulator.

Visually, it looks to me like the image has been scaled down to the point of losing definition, then scaled back up to the point of looking like a fuzzy mess.  Perhaps it has to do with the display resolution and/or density as well as having the "themed icon" feature enabled?  
...Hmmm... Yep. As an experiment, I decompiled the APK, replaced the existing `res/drawable-night/ic_syncthing_logo_black.png` file with the `/res/mipmap/ic_foreground.png` file, and it looks better, so I'd say this is caused by the fact that the 'night' mode icon png is 24x24 pixels while the normal icon is 432x432 pixels.

> I think we could merge the relevant part. Which lines of the huge diff are that?

I'm not a PC to be able to properly examine and/or test any real code changes, or try to get a build environment going at the moment, but it looks to me like `@drawable/ic_monochrome` is only referenced in two places:

- https://github.com/syncthing/syncthing-android/blob/e46ec1cfee2f670028a5d7676ac5de93156ba3bf/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml#L5  
  This is where Syncthing-Fork references the 24px `@drawable/ic_syncthing_logo_black` which makes it look like a fuzzy mess on my phone.
- https://github.com/syncthing/syncthing-android/blob/e46ec1cfee2f670028a5d7676ac5de93156ba3bf/app/src/main/res/layout/activity_firststart_slide_intro.xml#L28C18  
  This appears to be an icon change on the first-run intro page when in dark mode, so... I guess it's more part of the 'Migration to Material Design 3'.  IDK if it would look better or worse to grab this line without also doing the rest of the 'Material Design 3' changes.

Anyway, I also realized that the 'monochrome' icon they're using in the upstream repo is stylized differently than the colored icon which you're both using, so I'm thinking it might be better to take a lazier approach for the time being, and just change where you're currently referencing `@drawable/ic_syncthing_logo_black` to use `@mipmap/ic_foreground` instead of importing the upstream's `@drawable/ic_monochrome`.  (Though I do support the change to vector graphics instead of a PNG, but that change can be considered separately.)
https://github.com/Catfriend1/syncthing-android/blob/107eef50c33cb49869f3d2bea94f6a56b0d9b748/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml#L5

For reference, as you decide if you want to reuse the existing `foreground.png`, import the upstream repo's `ic_monochrome.xml` as your 'monochrome' logo, switch to using the new look for your colored logo too, or do something different, I made this:

Once again, the top row of icons are non-themed, and the bottom row are themed (with my chosen 'as close to black & white as the theming engine would allow' theme).  On the far left is what Syncthing-Fork currently looks like, on the far right is what the upstream Syncthing app currently looks like. The mid-left and mid-right options used the unmodified `ic_foreground.png` and `ic_monochrome.xml` files respectively, and for the middle one, I switched two instances of #FF000000 to #FFFFFFFF in `ic_monochrome.xml` to see how it would look in white.

![image](https://github.com/Catfriend1/syncthing-android/assets/1279475/6f8f3163-ac9b-4e21-9b4c-ec1831cd1628)

Also, since the`monochrome.xml` file had two paths, I thought it might be interesting to see which parts of it were painted by which path, and tried only changing the second path to white.  I was surprised how much I liked it, though... I'd likely never see it, since I use the monochrome 'themed' icons feature:
![image](https://github.com/Catfriend1/syncthing-android/assets/1279475/44a8dc03-c04e-47e1-bfd8-73f9ebddc2a5)

**Comment by Catfriend1** [comment]
Android 14 AVD with themed icons enabled:

![image](https://github.com/Catfriend1/syncthing-android/assets/16361913/e3a1dc7f-e06d-47ed-ac3b-5499718b3140)

**Comment by vada-pav** [comment]
@Catfriend1  but this icon still doesn’t look like the below one

![image](https://github.com/Catfriend1/syncthing-android/assets/59252456/ea445edf-83ce-4f37-90fa-2d331097725e)

**Comment by Catfriend1** [comment]
I don't care and you're right 🙂. This is not how I'd like to spend my time. As long as family and friends say the app is okay I am happy with it. That was the intention to keep it alive over years.
