### ISSUE TITLE
SyncThing Fork fails to start (crash)

### ISSUE THREAD

**Issue by rabu861** [Catfriend1/syncthing-android#1048]
### Description of the issue
Syncthing fails to start within syncthing fork (crash)

### Reproduction Steps
1. Starting SyncThing Fork
2. Folder scanning works and will finish sucessfully after a (long) while
3. From now on, SyncThing-Fork will start, but not SyncThing (although 'Force Run' status) --> Android notification from Syncthing-Fork: crash log (see below)
4. This is reproduceable, reinstalling SyncThing-Fork will not help

### Version Information
SyncThing Fork Wrapper Version: v1.26.1.0
SyncThing database size: 882M

### Device platform info
Samsung Galaxy S20FE 5G (SM-G781B/DS)
Android 13
One UI-Version 5.1
Kernel-Version: 4.19.113-27223811

### SyncThing Fork Log
--> see attachment
[Syncthing-CRASH-LOG.txt](https://github.com/Catfriend1/syncthing-android/files/13464500/Syncthing-CRASH-LOG.txt)

```

**Comment by ivanich** [comment]
Have the same issue but with oneplus7pro on custom crdroid rom with android13, original syncthing works fine with same imported settings.

**Comment by eightys3v3n** [comment]
Same symptoms; it was working until I updated it at some point. Since then I have been getting crash notifications and I can't force start it.
Oddly, it seems to start working when I turn on Log to File and Verbose Logging. Then it stops working again when I shut those off.
The attached log is a log before verbosity (I think). Then most of the way down I have pasted in the results after turning on verbosity.
[Syncthing-CRASH-LOG.txt](https://github.com/Catfriend1/syncthing-android/files/13465776/Syncthing-CRASH-LOG.txt)

**Comment by rabu861** [comment]
Unfortunately the 'log-to-file and verbose logging' workaround does not work in my case ...

**Comment by Xshakma** [comment]
Same Here. After the Last Update no sync. IT Crashes AS soon as it Starts.

**Comment by Catfriend1** [comment]
=> https://github.com/Catfriend1/syncthing-android/releases/tag/v1.27.0.0
