### ISSUE TITLE
Allow installing onto Nvidia Shield TV?

### ISSUE THREAD

**Issue by manojka** [Catfriend1/syncthing-android#1125]
Is it intentional that this fork isn't installable from the Google Play Store onto the Nvidia Shield? The older official Syncthing app is (was?) configured to allow it.

I see you've had lots of trouble with Play Store moderation, and if the right thing is to sideload these releases instead, I'm happy to, but the Play Store releases seem to be more up to date.

Thanks!

**Comment by Catfriend1** [comment]
Yes, I still have gplay approval. No one knows how long it will last because the original app was killed by gplay review for - in my opinion - no good reason.

I've decided to leave Google soon, so began to stop publishing on TV and doing reviews with them about that. The app will soon be hidden or deleted from play, my tickets are already running requesting my freedom back from google ;)
