### ISSUE TITLE
More on the "github" variant of Syncthing-Fork being debuggable

### ISSUE THREAD

**Issue by FixItKit** [Catfriend1/syncthing-android#1162]
Isn't the non-debuggable F-Droid variant updated later than the GitHub variant because of F-Droid's review process? You should build it like how the Google Play variant was built (developer-signed release build).

**Comment by Catfriend1** [comment]
Yes it's a little bit delayed. No, I won't make my debug build non-debuggable because it will take time to do it, and take again time if I miss something unavailable then and have to revert. You have a solution and that's fdroid.

**Comment by Catfriend1** [comment]
I'm attaching adb logcat regularly and expect some logs if users open tickets to see whats going on in an error moment.

**Comment by Catfriend1** [comment]
Does this work better?

https://github.com/Catfriend1/syncthing-android/releases/download/v1.28.0.0/com.github.catfriend1.syncthingandroid_github_signed_v1.28.0.0_a5050f98.apk

**Comment by Adhjie** [comment]
I have one unclear thing to ask. As a power user, should I use the debug one or the github signed one?
E.g., reset database, debug, debug option for syncthing fork in developer mode etc?

What are the differences between the 2?

Sorry for opening this again. I have an unanswered question from convo.

**Comment by Adhjie** [comment]
Okay. I'll stay on debug version then

**Comment by Adhjie** [comment]
I'm sorry to open this again. Should I make an issue, or just ask here; since it's just about package name and its implication.

So I noticed the latest package name is different it's syncthingNative, so should I migrate from debug version to syncthingNative, or you still will release debug version?

I also have read debug app being slower issue here, will this syncthingNative app be fine, with outputting logs for debugging?
I also have logfox for fallback in case I need to debug it, there's still a native option to debug it from settings right?

I'm sorry for the many questions but I need clear documentation on this, since I have many folders and Syncthing is my daily driver for syncing, any changes in Syncthing is critical in my workflow (day-to-day use).

Feel free to tell me this should be a separate issue, if my question here feels like necroing this issue (though, I would say this is still related since it's about debug package name version just syncthing package name using syncthingNative).

**Comment by Adhjie** [comment]
Alright, this is my last comment on this. I have migrated to SyncthingNative. Thanks for your continous hardwork on releasing version for android port to keep up with the desktop version.

This is my review in Gplay: (it was me) I forgot to put my @ there.

2nd review:
Sorry for the late reply, I notice the migration release note and go ahead backup and then import. No loss of settings, I'm now at the signed release.

Thanks for the ever quick release following Sycnthing desktop. 🙏🏽🙏🏽🙏🏽 Syncthing is really my main way of syncing, so I need to carefully think of what to do when any changes happened to the release.
