### ISSUE TITLE
GPLay publishing

### ISSUE THREAD

**Issue by AnthoDingo** [Catfriend1/syncthing-android#1186]
Hello,

I'm interesting to continue to publish your app on the Play Store.

**Comment by Catfriend1** [comment]
Hi,

Do you have a gplay account ready? How can I help you taking this over?

I fear the main problem could be reaching out to gplay policy review team and get approval for the various permissions the app requires at the moment. 

What is your suggestion on how to handle this in the future? Currently, the gplay build flavor uses the "lower permission sync_service" instead of the really "required other_service". The former is approved by gplay. I don't want to reappeal, so not touching this atm and bearing that until Android 14, the service stays alive correctly and dies on Android 15+ after Android's restriction limit of 6 hours .

The github flavor uses the required permission thus not closing after 6 hours run time. Should we do more of those in code to keep a gplay approval "as long as we can" or would you be willing to discuss / "fight" for this on play reviews?

**Comment by Catfriend1** [comment]
See detailed info about release variants and which is recommended to fit your needs.

https://github.com/Catfriend1/syncthing-android/blob/main/wiki/Switch-between-releases_Verify-APK-is-genuine.md
