### ISSUE TITLE
SD Card support

### ISSUE THREAD

**Issue by qazip** [Catfriend1/syncthing-android#178]
How is the support for syncing a folder in an external SD card? Is this something that can be done in this fork?

**Comment by qazip** [comment]
I've read the tips and tricks and also saw that you have an option to run syncthing as root.

**Comment by Catfriend1** [comment]
Related material:
https://github.com/Catfriend1/syncthing-android/wiki/Frequently-Asked-Questions

In short: It cannot be done; but the wrapper suggests the right path on SDcard where read-write access is granted by Android.
Technically: This is very complicated to solve and would need both large efforts on syncthing core and the wrapper project.

**Comment by qazip** [comment]
Is there any security/privacy issue when using the following option?:

"Create your destination folders under Syncthing's application-specific folder, e.g. /storage/emulated/0/Android/data/com.github.catfriend1.syncthingandroid/files"

It is what I am doing and I'd like some reassurance.

**Comment by Catfriend1** [comment]
Any folder on sdcard can be read by any app on your phone. More recent android versions restrict read access to those apps which asked you for storage permission (like syncthing fork does on the welcome slide).

**Comment by qazip** [comment]
Is that not true for the "normal" storage (non SD card storage)? That is, can't apps read that storage as well?

**Comment by Catfriend1** [comment]
Behaviour changed between android versions, also as I recall different ROMs (e.g. Cyanogenmod) had another behaviour mounting internal "sdcard" storage to /storage/ABCD-EFGH (instead of /storage/emulated/0) and then restrictions like for external sd card storage were applied. Honestly, I cannot assure you how "your Android version" handles it. It would be better to reach out to experts, e.g. on XDA forums and ask there as Syncthing-Fork just lets a native binary access the storage (and that is why limits from Android apply). This is on my opinion the least privilege level Syncthing gains. Other apps might have more privileges by following android's runtime permissions scheme.

**Comment by phuyuk** [comment]
The trouble started with Marshmallow - at least it did with one of my devices, which is still on Lineage 13.

That device is rooted, but I opted not to give Syncthing root access to solve the problem, since that feature is experimental and potentially hazardous. Rather, I've given Syncthing the needed 'write media storage' permission by editing the app's manifest in /data/system/packages.xml. This solution has been discussed elsewhere. It works flawlessly for me. External SD read/write, file-watching - all good. Most of my synced folders are on the external SD, including my entire music collection, pictures, and documents.

The only downside is that, after updating Syncthing to a new version, the permission is cleared by Android and has to be manually re-added. But it's just one line.

To be clear, though, I can only testify that this works on Lineage 13.

**Comment by Catfriend1** [comment]
Hi @phuyuk ,
what you describe matches my experience when I used cm13 back in the past :-).
Unfortunately it didn't work when I tried it almost a year ago with lineage14 on my lg-h815 phone running Android 7.x. If you like, feel free to make a short explanation for our wiki and I'll post it there for the other cm13/lineage13 users.
Thanks for your feedback.
