### ISSUE TITLE
How to end the app in one step?

### ISSUE THREAD

**Issue by merlinuwe** [Catfriend1/syncthing-android#355]
### Description of the issue
When I want to end your app completely, I cannot do this in one step by use the "Beenden"-Button ("end", "close", or "exit" I think). I also can open the window again by using the square android button at the bottom of my device, then I have additionally to swipe the window to the right to get the app really quitted. 

(Or did I overlook something?)

### Version Information
    App Version: every app, I always use the latest. 1.1.0.1
    Syncthing Version: v1.0.1
    Android Version: Android 7.1.1
    Device manufacturer: Medion 
    Device model: P10506 
(Also on the Smartphone Wiki Robby)

### Android Log
    adb shell / logcat
    or MatLog (search on GitHub) output

**Comment by Catfriend1** [comment]
Hi,
Thanks for reaching out!
There isn't a one step solution as the app acts as a service to keep the sync process running. Going to the drawer menu and selecting exit is the only way out. You may not (and technically don't need) to swipe it away from recents after you quit from the menu.

What you might be interested in is defining your run conditions so the app will exit any resource heavy parts by itself when you specified not to sync and start them back up automatically if run conditions match to continue the syncing process. The wrapper which needs to stay in memory to monitor the run conditions itself costs nearly no resources and doesn't drain your battery.

Short form:
- specify your preferred run conditions
- decide to let syncthing always stay in the background or quit the app manually when you see your one time shot sync is done.
- after quitting it's not syncing and no longer showing the notification and no longer monitoring run conditions.

If this expected behavior doesn't appear on your phone, please let me know and I'll reopen the ticket. Would need some logs then.
