### ISSUE TITLE
How to avoid changing the "Modification" date after synchronizing?

### ISSUE THREAD

**Issue by usodiario** [Catfriend1/syncthing-android#413]
Hello, after doing the synchronization, the original date of "modification" of the files changes to the current one.

In photographs it is a problem to maintain order by dates.

Is there any parameter so that the date does not change when synchronizing?

note: the "Creation" date does not change, but the "Modification" date does

Thanks

Synchronization from linux debian 9 to
Asus zenfone 5Q, Android 7.1.1

**Comment by Catfriend1** [comment]
Hi,

thanks for reporting this. Unfortunately, I can't help here (from the wrapper code side). This is caused by the Syncthing Core (also called "Native Binary") which is included in the wrapper app. Any features, bugs etc. regarding the functionality core, have to be discussed with the core team at https://forum.syncthing.net .

Kind regards
Catfriend1

**Comment by usodiario** [comment]
Thank you!
