### ISSUE TITLE
Release candidates on F-Droid?

### ISSUE THREAD

**Issue by felixwiemuth** [Catfriend1/syncthing-android#469]
Since F-Droid has a feature to point to a recommended version which is not necessarily the newest, I wonder whether you might want to also make the pre-release versions available on F-Droid so people can test more easily?

**Comment by Catfriend1** [comment]
Hi @felixwiemuth ,
Sounds interesting. How does that feature work?

**Comment by felixwiemuth** [comment]
I haven't tried it, but it seem to be the [`CurrentVersion`](https://f-droid.org/docs/Build_Metadata_Reference/#CurrentVersion) and `CurrentVersionCode` fields in the meta data.

Actually, look at [Syncthing-Fork's metadata](https://gitlab.com/fdroid/fdroiddata/blob/a82b8301dc1f92f77097a6149cc74633726de0bd/metadata/com.github.catfriend1.syncthingandroid.yml#L887) itself: `CurrentVersion: 1.1.4.1`, and this is what F-Droid labels as "Suggested" if you look at the different available versions, even though the newer 1.2.0.8 is there. (In this case somehow the F-Droid bot [set it back](https://gitlab.com/fdroid/fdroiddata/commit/599c851616e1e14c17fd67c81421ff2fec818380) to 1.1.4.1 after you set it to the newer.)

To include release-candidate builds, you just have to update [`UpdateCheckMode`](https://f-droid.org/docs/Build_Metadata_Reference/#UpdateCheckMode). But I am not sure whether there is a way to set `CurrentVersion` based on suffix. Otherwise you just have to update that field manually, should it not become the latest included version.

**Comment by Catfriend1** [comment]
The set-back came because there is a Problem with the dynamic version code generation in versions.gradle.
I'm not sure if this is worth work and time, remember that I'm more interesting in coding than release Management. Thats why build scripts have been automated as much as possible recently. F-droid team also told me that it is not good to allocate their time for Manual build and version set back for the recommendation. So at the moment: better not but if it gets more easy ans automatic on fdroids side, maybe sometime in the future.
There are also blockers because when I (exceptionally) do longer lasting release candidates (like the last week's) then there is a good reason: F-droid isn't fast enough with the build cycle for test builds/rc's when I need a user's feedback "now" to decide how to go on.
For example the RC aimed at building with Android q beta sdk which isn't additives m approved by fdroid yet I assumed, the same with go-dev or NDK bumps... This should easily go to github release channel and if possible to gplay beta.
Anyway: thanks for the idea. Maybe one day we'll also have some one caring about rc release stuff and then it wouldn't draw my focus away to do it additionally.... :-)

**Comment by Catfriend1** [comment]
Follow up: https://github.com/Catfriend1/syncthing-android/issues/473
