### ISSUE TITLE
Env var splitting bug at "=" sign

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#474]
Quote @olifre  from https://github.com/syncthing/syncthing-android/issues/1384 :

> Specifying the string:
`GODEBUG=tls13=1`
as environment variable setting in the debugging settings (which works perfectly well e.g. on Linux) does not save in the app, but the message that this string is invalid is shown. 
> ### Version Information
>   App Version: 1.2.0
>   Syncthing Version: v1.2.0
>   Android Version: Android 9.0.8 (OxygenOS)

**Comment by Catfriend1** [comment]
@olifre :
The fix will be part of an upcoming release.

**Comment by olifre** [comment]
@Catfriend1 Many thanks! :smile_cat:

**Comment by Catfriend1** [comment]
@olifre  A new release is up. Could you please report back to me if it works with setting the env var now?

**Comment by olifre** [comment]
@Catfriend1 Very nice! My first time trying the more "neko" fork - and I'm very pleased! 
Since with this fork, Syncthing TLS 1.3 out of the box (hooray!), I temporarily tried with:
`GODEBUG=tls13=0`
which both was accepted fine by the GUI in release 1.2.2.3 and effectively turned off TLS 1.3 as expected. 

So all is well :joy_cat:
