### ISSUE TITLE
The app forgets it already showed me the welcome screen.

### ISSUE THREAD

**Issue by fakheet** [Catfriend1/syncthing-android#491]
Sometimes after I accidentally kill the app with MIUI's RAM cleaning thing and reopen it, it shows me the welcome screen and makes me walk through the battery permission and geolocation settings: https://user-images.githubusercontent.com/19792485/64667896-41b6a480-d47d-11e9-9734-347ec57c5b12.png (don't mind the language).

As far as I can tell, the settings don't change or drop to defaults, so this may be just a cosmetic thing. 

I've previously used your app on an old smartphone with stock Android 4.2.2 and never encountered this issue. MIUI has four power saving modes, so far I didn't notice whether a selected mode makes a difference: the welcome screen appears from time to time on any of them, and so far I can't pinpoint why exactly it happens.

    App Version: 1.2.2.1
    Syncthing Version: v1.2.2-preview.3
    Android Version: Android 9, MIUI Global 10.2.4
    Device manufacturer: Xiaomi 
    Device model: Redmi 7A

**Comment by Catfriend1** [comment]
Hi,

Thanks for your report. I'm also using MIUI on Mi8 (10.2.3) and did not encounter any issue yet. According to https://github.com/Catfriend1/syncthing-android/blob/a98e5f63552f0a97ecebd19b1a9c315df8f32c33/app/src/main/java/com/nutomic/syncthingandroid/activities/FirstStartActivity.java#L113 the cause of the welcome screen showing again in your case is clearly android's battery optimization permission (as location is optional). Some (system) app or task killer "might" have revoked the permission resulting in the Slides to show up again on launch.
Some thing to note: I'm not 100% MIUI as I've removed system apps as far as possible without ending up the phone in a bootloop failure. So I suspect Xiaomi maybe has changed one of the system app behaviour I didnt notice yet for that reason.
This is pretty difficult to track down to the root cause... It comes to my mind that also googling or contacting the dontkillmyapp community/forum/site would help you?!
If I have an idea or encounter it myself during next MIUI update I'll get back to the ticket.

**Comment by regystro** [comment]
Same happens here. MIUI Global 10.2.30.0.
I turn off my phone every night and the next day Welcome screen wizard pops up when I launch the app. I give all permissions, but no way.
@Catfriend1 , could you please try restarting your phone and tell us if the same happens to you?

**Comment by Catfriend1** [comment]
@regystro Hi, doesn't happen here. I'm booting fresh every day after the phone shutted down at 0:00 clock completely. I guess this is because I'm blocking Xiaomi Updates with NetGuard Firewall and the local firewall. I'll recheck that when I grab my next MiUi Update ...

**Comment by Catfriend1** [comment]
And , btw, I've force removed all Xiaomi system apps which were possible (without breaking the system - bootloop).

**Comment by regystro** [comment]
Hi.

I finally managed to fix it this way: App drawer > Syncthing-Fork > Long press > App info > Battery saver > No restrictions

The setting was "Battery saver (recommended)" before, and that was causing the app welcome loop.

As you stated it was battery optimization related. Thank you!!

**Comment by Catfriend1** [comment]
Hmm I recall there is already a tip&trick in the app regarding xiaomi, so I'll add the advice there, too.

**Comment by Catfriend1** [comment]
Added a tip:
![image](https://user-images.githubusercontent.com/16361913/65385996-1dd54780-dd36-11e9-934e-8ec2339b82f5.png)
