### ISSUE TITLE
Option to turn off "Syncthing is running" notification

### ISSUE THREAD

**Issue by benshep** [Catfriend1/syncthing-android#494]
There is a persistent notification that says "Syncthing is running". Can I have an option to switch that off please? I realise I could force Syncthing notifications to never display, but then I wouldn't see any shared folder notifications.

The best thing would be a choice between levels of notifications:
- none at all
- only folder and device requests
- show progress when syncing
- always show "Syncthing is running" (the current default)

I just switched to this fork from the original Android Syncthing app, and I'm really pleased with it so far! Thanks for all your hard work on this.

**Comment by Catfriend1** [comment]
Hi,
Thanks for your feedback. :-)
I'll try to reconsider this when planning future improvements. Just to note: it was a strategic decision to have that notification because it's a side requirement caused by how Android works. Maybe I'll find a way to make it configurable later but that must be an implementation which does not reduce the apps (foreground) service reliability. ... I could imagine a "small use" option which only syncs when the app is foregrounded thus technically not requiring the notification permanently in place. At the moment it is required, as a service kill by android when the app is backgrounded could result in config or db corruption harming your syncthing instance critically.
More info is at a side topic : https://github.com/Catfriend1/syncthing-android/wiki/Info-on-battery-optimization-and-settings-affecting-battery-usage

**Comment by chilliger** [comment]
You can always hide the notification by using androids native notification settings for the app. At least this can be done for the presistent notification that is needed to not get killed.

**Comment by Catfriend1** [comment]
Until I find time to go after this detail, please use @chilliger 's solution. Will reopen when it's on my next todos.

**Comment by psoberoi** [comment]
Android 10 has a notion of "silent" or non-alerting notifications. For most apps, making a notification silent hides its icon - but for some reason, I see a syncthing icon in the notification area even after making the notification silent. Any idea why, and would this be easy to fix?

**Comment by Catfriend1** [comment]
It is a foreground service , it needs the icon by Android Developer guide Definition.

**Comment by Catfriend1** [comment]
And yes, it isn't the best for users that they must have the notification because of Android Design Guidelines and then discover they can use Android OS (not the app!) to hide what has been posed mandatory on them. The feedback has (unfortunately) go to Google here.

**Comment by psoberoi** [comment]
Thanks for the explanation!
