### ISSUE TITLE
Bypass splash screen/battery optimization permission

### ISSUE THREAD

**Issue by Verfassergeist** [Catfriend1/syncthing-android#501]
Introduction: If you have issues with this fork, feel free to post them. I'll look into them if a good reproducer or log is provided.

### Description of the issue

Unable to bypass battery optimization splash screen.

### Reproducer

Launch app on Kindle 8HD 2018. FireOS does not provide access to battery optimization or may not have the functionality to begin with due to OS fork from AOSP. Toast message indicates that battery optimization is not available on device, but there is no way to not grant the privileges.  

### Version Information
    App Version: 1.2.2.5
    Syncthing Version: 
    Android Version: Android 7/ FireOS 6
    Device manufacturer: Amazon
    Device model: 8HD 2018

**Comment by Catfriend1** [comment]
Related: https://github.com/Catfriend1/syncthing-android/issues/442

Hi @Verfassergeist

Could you please post the Info requested in the linked issue? I think we'll handle those cases like we already do regarding Android TV boxes. If that's not possible we could try to make an exception but SyncthingNative had shown in the past it does not work reliable on Android without the permission because it can be killed by the OS causing serious database damage. That is why the permission was made mandatory to get everyone on a "same basis" regarding bug reports of "Syncthing suddenly no longer running/syncing" and preventing damage / data loss caused by corruption.

Thank you.

**Comment by Catfriend1** [comment]
Reminder:

> I need the output of:
> adb shell
> getprop | grep ro.product

**Comment by Catfriend1** [comment]
Reminder:

```
I need the output of:
adb shell
getprop | grep ro.product
```

**Comment by Catfriend1** [comment]
Reopening when required info arrived.
