### ISSUE TITLE
Tasker: force Start syncthing in background

### ISSUE THREAD

**Issue by heX16** [Catfriend1/syncthing-android#544]
I want start syncthing from Tasker using "send Intent". This is necessary to enable the sync when it is completely unloaded from memory.

I found [this recipe](https://stackoverflow.com/questions/16135157/how-to-start-service-using-external-intent), but it does not work.
Apparently you need to add: **android:exported="true"** in com.nutomic.syncthingandroid.service.SyncthingService (or com.nutomic.syncthingandroid.service.SyncTriggerJobService).

The [documentation](https://developer.android.com/guide/topics/manifest/service-element) says that by default it is prohibited and you need to add this flag or filters.

 It should be noted that [this recipe](https://github.com/syncthing/syncthing-android/wiki/Remote-Control-by-Broadcast-Intents) does not work in this case - the program does not load into memory if it is completely inactive (it must be turned on manually). and in any case, completely external control of the modes does not suit me - I am completely satisfied with the existing control.

P.S. thanks for your fork!

**Comment by Catfriend1** [comment]
Hi,

Thanks for digging into this. I haven't checked for a long time with tasker, to admit... 
The correct documentation for the fork is at: https://github.com/Catfriend1/syncthing-android/wiki/Remote-Control-by-Broadcast-Intents

Please try that again and tell me which device manufacturer, model and Android version you're using.

I'm a little bit careful about setting exported to true without really being required to do so because Google last time sent me a security warning about that flag present in the apk and forced me to remove it (so the app would still be eligible for gplay publishing).

Let's see if we can find a way of using Tasker without the flag first.

**Comment by Catfriend1** [comment]
Closed until it gets more clear what has to be fixed.
