### ISSUE TITLE
[FR] Show device last seen on devices tab

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#569]
![image](https://user-images.githubusercontent.com/16361913/89934551-0b475380-dc11-11ea-8736-a5da823882da.png)

**Comment by DrPhant0m** [comment]
I was referred here via a response to my review of the Syncthing app for Android.

I'd like to see a feature such that a notification will be produced on the device being backed up (in my case, an Android phone) if a successful connection to the backup location (in my case, a home server) hasn't been established for XX hours/days.

For example...  I have our phones set to back up the internal and external storage to my home server.  We lost power at home, and when the server came back on, I forgot to restart the SyncThing service, so our phones were not being backed up for about a month.   When my wife's SD card went bad, I found that our latest backups were a month old, so she lost a month of pictures of our kids.

If she had gotten a notification that it had been "too long" since a connection had been made from her phone to our server, I would have investigated it, and found that I simply needed to start SyncThing on the server.

Please consider this!   Thanks!

**Comment by Catfriend1** [comment]
So this is the endpoint:

`GET /rest/stats/device
`

Response:
```
{
  "DEVICE_ID": {
    "lastSeen": "2020-04-13T16:06:41.1124246+02:00"
  }
}


```
