### ISSUE TITLE
[FR] Feature Request: Different synchronisation conditions per folder

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#57]
Quote from @cdrfun at https://github.com/syncthing/syncthing-android/issues/1225
> Hi there, it would be great if you could define different synchronisation conditions per folder.
Possible use case:
One folder which is important should always be up to date - no matter if I'm on WiFi or battery. For me this would be my folder with the password manager database.
Other folders like photos could be synched only with WiFi and/or battery.
Would this be possible given the current architecture?
What do you think about this idea, aside from technicalities.
Greetings!

**Comment by Catfriend1** [comment]
Hi @cdrfun !
I'm currently working on many improvements for the wrapper. Yes, it would be possible and I've already made a development for this feature that fits to your description. Thanks for writing it up. When I'm done with the compatibility and bug fixing stuff I'll go on this challenge.
Kind regards
Catfriend1

**Comment by Catfriend1** [comment]
Folder properties draft:
![image](https://user-images.githubusercontent.com/16361913/45900616-91214200-bde0-11e8-8502-13e6bf72d4ee.png)

Reference: https://forum.syncthing.net/t/selective-sync-for-syncthing-android/12048

**Comment by Catfriend1** [comment]
@Pazuu Do you like the above idea?

**Comment by Catfriend1** [comment]
Ok, I thought about this a lot ... I'm going for an implementation where every device and folder has a submenu "specify my sync conditions so I know when syncing this object's stuff is valid" e.g. Wifi with name  "HOME" for folders A,B and Wifi with name "FRIENDS" for device "FRIEND".. All in all, those options would be expert options, so a checkbox needs to be ticked in the settings to make them visible. A "0815" user would else be confused by all those run conditions ;)

**Comment by Catfriend1** [comment]
Draft:
![image](https://user-images.githubusercontent.com/16361913/45930823-fef67680-bf64-11e8-9ce2-0c3be1195a5c.png)

**Comment by Catfriend1** [comment]
Yes, thats intended.

**Comment by Catfriend1** [comment]
Hi,
the intermediate status is that I've completed the UI implementation. I will now work on the technical part to make per-folder sync conditions possible.

**Comment by Catfriend1** [comment]
The feature is implemented and released.
See #66 and https://github.com/Catfriend1/syncthing-android/releases/tag/v0.14.51.6 (release page).

**Comment by cdrfun** [comment]
Really nice work! 
I had some time to test today, and here is what I've found. (If needed I'll create a separate issue(s)). Some if my labels might not be correct, because I'm using the German version. I use numbers for better referencing, not to indicate any importance:

1. Folder-Sync condition Start at selected Wifi can't be activated when a option page for an folder is opened where start with wifi is activated. When deactivating/activating the option start with wifi, the option Start at selected Wifi can be set.
2. Currently folder sync conditions can only limit the folders sync conditions compared to the global conditions. I understand that it is good to have some kind of a global limit. But this puts the user in a tricky situation when he wants one folder to "always sync". He has to max out the global conditions and limit all folders bit the always sync folder. additionally he has to remember to limit all new folders, or he will use more traffic than he thought. Perhaps a separation of syncthing starting conditions and default folder conditions would be a solution.
3. The Folder-Sync condition dialog has a checkmark in the upper right. This is not necessary, because changes are saved when going back (either using the arrow in the upper left or the back button). Additionally when pressing the checkmark the folder options dialog is revealed and here is the trash icon at the same position. This is not consistent.
4. When wifi connection is lost, and some folders are configured to run on mobile, syncthing seems to restart completely instead of just pausing non mobile folders. When the wifi connection is regained, syncthing just unpauses the folders - which is correct.

**Comment by Catfriend1** [comment]
Thank you for your detailed feedback ! @cdrfun
Please tell me which APK version / release you used for testing this. I guess (1) is already fixed by 0.14.51.8+?

**Comment by cdrfun** [comment]
Doh, my bad. I've used the last released apk version: Syncthing v0.14.51.8 / 4171

**Comment by Catfriend1** [comment]
@cdrfun I'll take the other points on my development plan. Will take some time but definitely is where I want to get in the future to transition over to the new run conditions without global vs. object mismatches.

**Comment by Catfriend1** [comment]
@metal450 I know this is not about intents, but if you like to unpause your folders according to run conditions maybe this is for you...

**Comment by metal450** [comment]
Cool :)  Though it doesn't seem like it provides a way to manually sync specific folders only on-demand, which is what I'm trying to accomplish.

**Comment by Catfriend1** [comment]
Maybe you can use the Tasker intent control in the fork's app settings and combinate with http post requests to Syncthing's REST Api sent by tasker. Pausing and unpausing shouldn't be difficult by the api. :)

**Comment by metal450** [comment]
>> Pausing and unpausing shouldn't be difficult by the api. :)

In the API docs, I only see a way to pause per device - not per folder: https://docs.syncthing.net/rest/system-pause-post.html

**Comment by Catfriend1** [comment]
According to what imsodin wrote on the forum the docs are outdated... Please ask him on the forum, In expect this endpoint also works for folders.

**Comment by metal450** [comment]
Sounds good, thanks for the pointers :)
