### ISSUE TITLE
sync status at 95%

### ISSUE THREAD

**Issue by PetziAt** [Catfriend1/syncthing-android#607]
My sync state is always at 95% but everything is synced.

![Screenshot_20200120-165158_1](https://user-images.githubusercontent.com/4418572/72740358-d062cd00-3ba5-11ea-8d92-436e6fa07a22.png)

**Comment by Catfriend1** [comment]
I guess you need to check the other side. Is the partner device sendonly?

**Comment by Catfriend1** [comment]
I guess that's a "no problem" regarding the native and not the wrapper. Another side is probably pending deletions. If it doesn't solve, please go to forum.syncthing.net and speak up there because it is a general syncthing related problem.

**Comment by lucker999** [comment]
Have the same problem. 95% and all folders intact. As I checked, the reason for it (might) is that some old (needed) folders exist in PC sync folder. I use it to upload my backup from Android to PC. The settings as follow:
- on Android (5.1): send only folder (automatically while it's on SD-card
- on PC (Windows 8.1 with SyncTraysor): receive only folder

I discovered that if I remove the old folders from PC then the sync is completed. So, basically, the 95% sync notification on Android represents the intentional "out of sync" state, while the old backups on PC should be there, but (in order to save some space) not on Android.

I am not sure if it's expected behavior or I miss some additional settings (like add DO_NOT_DELET.txt file in the PC folder or something), but it's really annoying.

**Comment by Catfriend1** [comment]
The ticket should go upstream to the Syncthing project as we display what Syncthing(native) tells us on the wrapper UI.

**Comment by cauerego** [comment]
can we see this native data point (the 95%, or 69 in my case) on the native app?

can't find a link to the ticket that should be there.

**Comment by Catfriend1** [comment]
No, just the percent are on the UI, not the files in question. You have to use the web UI.
