### ISSUE TITLE
App has hang bug

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#62]
Issue quote from https://github.com/syncthing/syncthing-android/issues/1226
@JonasT
This problem is fixed in Syncthing-Fork. Feel free to try it from this repo and provide feedback.

If you have issues with this fork, feel free to post them. I'll look into them if a good reproducer or log is provided.

### Version Information
    App Version: 0.x.y
    Syncthing Version: v0.x.y
    Android Version: Android x.y / Cyanogenmod x / ...

### Android Log
    adb shell / logcat
    or MatLog (search on GitHub) output

**Comment by JonasT** [comment]
I understand, but I'm not interested in running release candidates of syncthing (the core application, not the android frontend) since in the past they have proven quite unreliable, even including that one data loss bug that affected a lot of people and wasn't pulled out of the release candidate branch for days.

Another issue, the syncthing-fork would have separate settings, wouldn't it? I have a *lot* of folders, so it would take a while to re-enter them all.

Summed up this is useful information, but not really a helpful substitute for getting a properly working stable release into the regular `syncthing-android` app

**Comment by Catfriend1** [comment]
Side note @JonasT Synching fork has also a solution to https://github.com/syncthing/syncthing-android/issues/1228 . You can leave the service checkbox off and run conditions will be respected and monitored - even in the background - until you hit the exit button or android gets low on resources and kills the app forcefully.

**Comment by JonasT** [comment]
I want it as a service that isn't stopped by Android (my phone isn't that beefy so things get stopped all the time), so that doesn't sound like something I would use. I am mainly looking for a "just stop doing things until next reboot" switch that doesn't change any of the other settings, which is what I would expect the "Exit" button to trigger *if* it was actually available with the service enabled

**Comment by Catfriend1** [comment]
The battery eater is also fixed, see changelog.

**Comment by JonasT** [comment]
Any ideas when at least the core syncthing version bump will go back into syncthing-android? (since for the reasons mentioned above, I don't feel like it's a good idea for me to switch to the fork)

**Comment by Catfriend1** [comment]
I'd suggest to try if the improved checkboxes and run conditions help you out. As it cant be done "against" android os nature, an exitable service cannot be implemented. On my phone, the service is active all the time and after things got fixed it doesn't drain one single percent of battery if run conditions don't apply.

**Comment by Catfriend1** [comment]
Sorry, merging upstream is currently not in a near time range but maybe in the future. This a long story...
You can install the fork as a separate app and importing your config is supported. But: be careful not to run both apps along at the same time, only one may run the other must stay exited.

**Comment by JonasT** [comment]
Regarding the Exit issue / new checkboxes:

I'm not sure what else I should possibly try out or how that would change anything :man_shrugging:  (I don't really see how any of them are relevant since can already disable the service now, and running it over a longer time as a not-service simply isn't a very good idea on an Android phone with less memory usage, is it?)

Issues are prone to pop up in the future. This is why I still believe this is useful. However, I understand if you say it's not worth the hassle to implement if it means fighting Android too much. Nevertheless, I still believe it'd be useful to have.

Regarding the broken syncthing in `syncthing-android`:

Just for clarity, I am **not** suggesting to merge anything happening here in the fork, but to timely bump the version of syncthing shipped with the regular `sycnthing-android` to the latest stable that is also available for desktop. Of course if that requires any additional changes to the wrapper, then that might not be feasible :cry:

**Comment by JonasT** [comment]
Sorry, I forgot to ask something else: if I import my config into the syncthing fork, can I ever go back to `syncthing-android` / import it in the other direction? If yes, then I might actually give it a try, at least as a temporary alternative

**Comment by JonasT** [comment]
Thanks, will do! And thanks a lot for your responses & help, that was extremely insightful

**Comment by Catfriend1** [comment]
@JonasT Sorry to correct you, but the fork currently uses 14.51 release in APK Version 4166, 4167.

**Comment by JonasT** [comment]
Will it stay on stable versions of syncthing now? Sorry, maybe I saw this incorrectly, just seemed to be on release candidates at some point. If you're going to stick to stable mostly, then I'm definitely interested!

**Comment by Catfriend1** [comment]
I want to prioritize stable versions but rc's are good for me to adjust the wrapper before a stable release if API things change. You can always determine from my apologies release names which versions are rc and which ones are stable. E.g.
v0.14.51.(number) contains a stable syncthing core
v0.14.51.rc.(number) contains a release candidate syncthing core.
Both of them go to fdroid but you can freely decide if you want to use the rc's.
