### ISSUE TITLE
Sync status not working

### ISSUE THREAD

**Issue by TheCrowned** [Catfriend1/syncthing-android#658]
I am a bit confused as to what the sync status should show. My case is that it shows 
- the app in _Folders_ view shows _Out of sync_
- top part of the app shows a green badge with correct sync percentage
- the notification says 0% completed
- the _Devices_ tab shows _Syncing_
- the webgui accessed from the app shows correct status

I provide screenshots:
![Screenshot_Syncthing-Fork_20200523-092017](https://user-images.githubusercontent.com/7880569/82724551-2de36380-9cd7-11ea-9afc-ef244ef7bcd7.png)

![Screenshot_Syncthing-Fork_20200523-092025](https://user-images.githubusercontent.com/7880569/82724553-2de36380-9cd7-11ea-83ee-c9910808c0cb.png)

![Screenshot_Syncthing-Fork_20200523-092047](https://user-images.githubusercontent.com/7880569/82724554-2e7bfa00-9cd7-11ea-8acd-588eb168c1c6.png)

![Screenshot_Syncthing-Fork_20200523-092013](https://user-images.githubusercontent.com/7880569/82724548-2cb23680-9cd7-11ea-879c-baff9d59d9ad.png)

### Version Information
    App Version: 1.6.0.0
    Syncthing Version: v1.6.0-preview.2
    Android Version: OmniROM with MicroG, Android 10
    Device manufacturer: OnePlus
    Device model: 6

**Comment by Catfriend1** [comment]
Hi,

Thanks for your detailed report! Most things still look good when I have in mind what the UI code does so 66% is expected as a whole "virtually calculated" completion and cannot be compared to the folder's web ui percentage because the whole is calculated from folders and devices.

I still don't know why the device status didn't come in which /could/ explain the wrong status in the status bar and the "syncing" on the device tab with no percentage which is inserted by the wrapper as a fallback guess when there's heavy traffic but SyncthingNative doesn't report the syncing status to the wrapper.

Let's take those steps:
- I'll make v1.6.0.3 available soon containing upstream's Syncthing v1.6.0-rc.5. Please update to that version then and tell me if it works better.  
- I'm at minimum expecting the out of sync might go away (if you haven't changed anything unexpected in the files while syncing so Syncthing would be right emitting this state) and the devices should show the percentage short after starting to exchange data.

If you see the forum, 1.6.0 rc.2 had issues with the states.

**Comment by Catfriend1** [comment]
@TheCrowned  The new release is here:
- https://github.com/Catfriend1/syncthing-android/releases/tag/untagged-829e9c0a366f19d8fdb4
- GPlay APK: https://github.com/Catfriend1/syncthing-android/releases/download/v1.6.0.3/com.github.catfriend1.syncthingandroid_gplay_v1.6.0.3_ee5ad786.apk
- GitHub APK: https://github.com/Catfriend1/syncthing-android/releases/download/v1.6.0.3/com.github.catfriend1.syncthingandroid_v1.6.0.3_ee5ad786.apk

**Comment by Catfriend1** [comment]
Let's reopen this if the new release turns out to have problems, too. Maybe we should also consider reporting it upstream at forum.syncthing.net then.
