### ISSUE TITLE
URL option for photo-sharing use case

### ISSUE THREAD

**Issue by MadCamel** [Catfriend1/syncthing-android#676]
I've been using syncthing-fork as a replacement for commercial services for quite some time. To replicate useful photo/video sharing functionality available in other cloud-sync apps I have one of my syncthing folders is exposed via https://. 

When I want to share a photo from within my android gallery app, I select Share With, Syncthing, and then save the file to my public folder. This works well for the most part but there is one huge annoyance: I have to manually build the URL each time I want to share it. For instance if I upload IMG_ABC123123.jpg and I want to share the URL to it via SMS I end up manually typing in https://my.site.com/IMG_ABC123123.jpg, for each file I want to share publicly. Dropbox etc make this much easier.

It would be amazing if syncthing-fork had a base-URL in its settings where I could enter https://my.site.com/ and provided a way for me to copy the full URL to the image in the above workflow.

If this is out of scope I totally understand.

**Comment by Catfriend1** [comment]
Hi,  I'm not opposed to such special function even if it hasn't got directly to do with what's Syncthing's core mission. What maybe could be done:

- add an expert option in the settings for the special behavior, this reveals the base path text setting below if enabled
- if applicable, make a "post copy to Syncthing" dialog which is nicer than the current toast popup which displays the result of the copy operation
- use the new dialog which pops up after the save operation to offer a button : share the url with... And generate an intent for being received by other apps like WhatsApp, telegram, etc. So Android does pretty much the rest of the hand over into your favorite chat app .

Do-able, I think, but honestly nothing I will put on my schedule. I've got enough to handle with the Android 11 again-and-again API compatibility rush, unfortunately deferring features I wanted to do since ever long because I don't know if it's worth to cast a new feature (especially run conditions) now and then make them compatible with all Android versions again. Yeah, typical dev worries. Anyway thanks for the suggestion!

**Comment by Catfriend1** [comment]
So, I was close to implement it, and then I found the "Piwigo" Open-Source picture albums. I think this is exactly what covers your need. I've set it up on my Syncthing always-on device and it can automatically make albums out of a well-kept folder structure. It does not require to duplicate your files "because of the other software piece" which was one of my main arguments when looking for a nice picture album tool. Piwigo can also help you sharing albums publicly or privately (via mail, via link, via account). This way, I no longer see the need why this should be Syncthing-Fork's mission.
