### ISSUE TITLE
Run according to schedule - manual override

### ISSUE THREAD

**Issue by matt6575** [Catfriend1/syncthing-android#719]
I'm using the Run according to schedule option but have had several instances where I wanted the sync to happen immediately. Could there be a "Manual Run" button that would do a one time sync?

**Comment by Catfriend1** [comment]
Hi, there already is a "force start, ignore run condition" button on the status tab to do this without reconfiguring deep in the menus.

**Comment by matt6575** [comment]
Crap, sorry I don't know how I overlooked that. That works a expected.

Only thing I'd maybe add to that would be the ability to initiate a one time force start that after all folders have to been synced it automatically reverts back to "Follow Run Conditions" I could see myself forcing a run and while it's syncing do something else on the phone and forget to set it back. I could however live without that ability but it might be nice.

Thanks for the work you put in to this. Do you accept donations at all for your work?

**Comment by Catfriend1** [comment]
No problem. :) A link is on top of the github main readme (lp patrons). But honestly I'm not sure I could do your feature request "this year".

I think the "wait to complete" is doable, but it's not that easy. It has beeb discussed for official and fork a long time, the core devs always correctly answered that one shot syncs aren't syncthing's goal because it sync continuously. What we get from a dev point is Syncthing(native) tells us: Starting, Idle, Disconnected, Connected, Syncing (if the status is holding on for longer than just a quick "50kilobyte" transmission for us to recognize in the android wrapper), Idle. And we would need to track those state changes like an industrial robotic process chain. With the hard part at: what will we do/how long will we wait if one step does never occur? 10 seconds each? Or better 500ms as my connections and server is fast? Why I waited even so long to implement the force start was not only the core team and some users told me this could be unwise, I also liked to br sure before starting on this I have a minimal code change in sight to not mess up code and probably the user being able to understand what every X option does. Definitely not against the feature, but it should be easy and well placed. For example having huge linear code blocking thread execution around is a no go, as that could end in a battery eater or incorrect shutdown eating your Syncthing database. If I have a cool idea I'd maybe make a sort of internal process chain state tracking in the EventController of the app, log down the (start, idle, syncing, idle) and also log a guess when it would have decided to go off after completion. I'd then ask you to test and provide that log if the app determined the correct time of completion. If that works well, suggestions for baking the feature into the UI could be discussed. Maybe this write up also attracts someone else to try it and make a PR, let's see who has the time first ;). I'll return some day to this, but don't know when.

**Comment by Catfriend1** [comment]
@matt6575 I think the PR #768 will make your life a lot easier as you could launch "another 5 minutes time windows" immediately from the quick settings tile bar.

**Comment by matt6575** [comment]
Thank you very much for calling my attention to the new feature. This should do exactly what I was wanting.
