### ISSUE TITLE
Suggestion: publish app on XDA Labs

### ISSUE THREAD

**Issue by zilexa** [Catfriend1/syncthing-android#723]
Just a suggestion, to publish the app on XDA Labs Store, besides F-Droid. 

https://labs.xda-developers.com/

It contains apps that are not always FOSS, but does have very useful apps like adbockers, Youtube Vanced, Mixplorer (fully featured file manager, alternatives are usually paid) etc.

**Comment by Catfriend1** [comment]
Hi, thanks for the pointer. Sounds good, but reading this ( https://www.xda-developers.com/big-changes-to-xda-forums-are-coming-soon/amp/ ) I am concerned it will not last long as a positive effect of distributing the app without problems.

quote:

"The main XDA app on the Play store will undergo a major update in the coming weeks to work with the new forum backend. Support for XDA Labs is tentatively ending at the end of this year, but we’re exploring options to keep it going, because we know that a small handful of developers use Labs to distribute their app.  We’re hoping to open source and find a team to take the reins and continue development, and if you’re a developer that wants to work on Labs, send a PM to svetius. We’d be delighted if Labs could continue, but as a small technical team and we don’t have the resources to maintain it. Over the coming weeks we will be taking steps to inform any developer that is actively using Labs about this change so they can plan accordingly"
