### ISSUE TITLE
[Question] Release variants

### ISSUE THREAD

**Issue by cybe** [Catfriend1/syncthing-android#739]
Hey!

There are currently 3 release variants: github, gpllay-full and gplay-light. What is the difference between the latter two?

Background: I recently updates to Android 11 and needed to reinstall Syncthing-Fork to utilize the full disk access permission. I chose the gplay-full variant which worked. However, afterwards the app got updated through gplay-store which in turn removed the permission again. Now I switched to the github-variant. This also works and gplay isn't trying to auto update the app.

Can you perhaps briefly state the difference between the release variants?
~~Also: Why is there no fdroid-variant?~~ Found it, it resides in a separate [repository](https://github.com/Catfriend1/syncthing-android-fdroid).

Thank you!

**Comment by Catfriend1** [comment]
Hi,

gplay light is "what Google wants", it's a "shitty version" to hold on extending our userbase so the project attracts new play users and gives them "just a wrapped working Syncthing" as a starter. gplay-full is for every user that got stuck during Google's Android 11 update and needs some thing to update to manually in order to be able to exporz their config (and keys) and then be able to move to the GitHub/F-Droid version.

The functionality of gplay-full, github, f-droid releases are the same (because it's the same permission manifests and code underlying).

**Comment by cybe** [comment]
Thank you, appreciated!

**Comment by hgj44d** [comment]
I still don't get what the current differences between github, fdroid and gplay versions are. Could you please explain it further? Thanks ;)

**Comment by Catfriend1** [comment]
Preferred: F-Droid
For "do it yourself" users: GitHub
For beginners: GPlay Store

F-Droid and GitHub = same
GPlay = currently the same, may be restricted/have less features enabled in the future due to G's restrictions.

**Comment by hgj44d** [comment]
Thank you for your answer! I will now just install the F-Droid version, but your statements are still confusing:

> F-Droid and GitHub = same

When they are the same, why do they even exist in two seperate files? When they are the same, why they have a different file size?

I really don't want to nag, but just want to make it easier for new users because I'm sure that I'm not the only confused user :)

**Comment by Catfriend1** [comment]
It's the same app, but made by a different build system.

**Comment by hgj44d** [comment]
Thanks, can you add this to the README.md file?
