### ISSUE TITLE
Documentation - Privacy policy document

### ISSUE THREAD

**Issue by princekelly1** [Catfriend1/syncthing-android#78]
Hi,
I think an app such as this, needs a proper privacy policy document. Which I will be glad to draft one for the project, while I'm constant communication with you. 
I await your response.

**Comment by Catfriend1** [comment]
Hi @princekelly1 ,
thanks for reaching out :). I think this is generally a good idea, I'm just a little bit unsure which repository is the right place for a privacy policy statement. The syncthing wrapper itself doesn't collect any data from the user so it doesn't send anything to any servers. But the point is, the upstream syncthing binary may or may not communicate with the syncthing.net servers (for update checking, usage data after the user opted in, relay and discovery servers) according to user's preferences.
That said, I'd welcome a PR with a privacy policy draft and would even link that from the app (link from app to github wiki, for example). You do not necessarily have to care about the UI part as I can do it. The "text" is enough, let's start in english.
Probably better would be to ask at github/syncthing/syncthing project in parallel, because if the upstream project - which also runs on platforms other than Android - picks up the request, we could use this wrapper on android to display the statement the upstream web UI serves.
Best regards
Catfriend1

**Comment by Catfriend1** [comment]
Feel free to come back to this topic any time, then we can reopen it as soon as this is actively worked on.

**Comment by Catfriend1** [comment]
Done.

**Comment by Catfriend1** [comment]
needs update: https://syncthing.net/android-privacy-policy/

**Comment by Catfriend1** [comment]
https://github.com/Catfriend1/syncthing-android/commit/5a5409f7367d3022b168bf64364c6e53dec0411e
