### ISSUE TITLE
Syncthing-Fork occupying 5GB, Synced folders aren't close to 1GB

### ISSUE THREAD

**Issue by Elaborendum** [Catfriend1/syncthing-android#825]
### Description of the issue

![image](https://user-images.githubusercontent.com/71190696/123023007-458a9100-d39c-11eb-8def-3a6a90db9f67.png)

System reports that Syncthing-Fork is occupying ~6GB of storage, despite the fact that the only 2 folders that I sync are both less than 1 GB combined. I may have had file versioning activated for one of the folders, but I don't remember if it was always like that or if it was a recent attempt to figure out what was wrong with it. 

Anyway, at this point both have file versioning off, I also moved said folder from SF's data folder and SF now occupies about 5.89 GB. Am I just doing something wrong? Should I just erase all its data and start from scratch by importing my settings?

### Reproduction Steps
I don't exactly know what I did to get it like this, so I will describe what lead me to "discover" this.

That folder mentioned earlier previously contained about 1GB, Syncthing-Fork was also occupying a similar space (at least last time I checked) and was shared with 3 devices. Then, I added a fourth device (also a phone, also using Syncthing-Fork) and from there I erased most of it and a while later I turned on SF in my phone. During this, suddenly my storage got almost completely full, 6GB filling up in a flash.

### Version Information
- App Version: 1.16.0.6
- Syncthing Version: v1.16.0
- Android Version: Android 10
- Device manufacturer: Samsung
- Device model: A20

### Device platform info

```sh

```

### Android Log

```sh

```

**Comment by Catfriend1** [comment]
Hi @Elaborendum ,

thanks for reaching out, are you familiar with adb shell debugging ? This would ease to check using the "du -sh /path/to/app/internal/storage" how much space is occupied by which folder. I suspect it's synced data, but if you have Syncthing running all the time and a problem hits, there might be huge database or logs created by the native running within the wrapper's context. Maybe also a bug report at forum.syncthing.net can help, if it turns out not to be your synced files (or historic versions) taking up the space. On my phone, currently at v1.17.0.0 (preview), everything works fine. Space usage is not abnormal.

Kind regards,
Catfriend1

**Comment by Elaborendum** [comment]
I'm not entirely familiar with it, you mean the folder in Android/data? If so, adb returns 180K. 

Just in case I also checked my synced folders and got this surprise, my main synced folder returned 5.4G (SF says it occupies 28.5MB) and the second one returned 15M (SF says it occupies 517KB). So I take it the problem is historic versions? How do I clean them up?

I only occasionally run Syncthing to transfer some files, its never constantly running in any of my devices.

**Comment by Catfriend1** [comment]
@Elaborendum  I'd suggest temporarily lowering the days of the trashcan versioner in the folder options to clean up historic versions earlier than the default X days. Otherwise, a PR is needes to make a button "empty version folders" wirh SAF/all files support.
