### ISSUE TITLE
Execute syncthing using JobScheduler/WorkManager API

### ISSUE THREAD

**Issue by bt90** [Catfriend1/syncthing-android#832]
The intended use case of

> Periodically syncing application data with a server

Seems like a good fit for syncthing. We can also map most of our run conditions.

https://developer.android.com/topic/libraries/architecture/workmanager#reliable

**Comment by Catfriend1** [comment]
This is a very good finding, @bt90 . Thank you. I'm sorry to not have time at the moment to look into this as an enhancement.

**Comment by bt90** [comment]
All good 😉

**Comment by Catfriend1** [comment]
Did some reading and found a lot fits perfectly for Syncthing running multiple "one time shot syncs" in the background. Constraints to run look good, although onenis missing: https://stackoverflow.com/questions/58837075/add-check-for-local-wifi-connected-constraint-on-workmanager-in-android

**Comment by bt90** [comment]
Wouldn't hurt to start the job regardless of the network situation and do the more fine grained checks before starting the syncthing process.

**Comment by Catfriend1** [comment]
Yeah, just one thing isn't clear to me yet how to change the app architecture : we run Syncthing and let the ui pull data for config/info/status. if we do it fr WorkManager, how could we use the same routine to get it running for config purposes when we need to "get the wrapper's gui" up? would we need two mechanisms ? the old and the new in parallel? hoe would we ensure, no second instance is started by WM while the app itself runs one because the user interacts with the config?

**Comment by bt90** [comment]
I thought about that as well. Ideally we end up with two modes of operation:

* manual/config mode
   * everything happens in the context of the app
   * the user is able to configure syncthing
* auto/sync mode: Syncthing is only run via the WorkManager

The interesting thing is if and how the app can communicate with currently running background jobs.

**Comment by srett** [comment]
I just remembered this issue since I've been fighting with WorkManager recently, so hopefully my findings will help if this will be tackled one day. So far I have a simple app that creates periodic work that should fire once an hour, no run conditions, and do an HTTP request to a log server.
These are my results after applying all the tweaks I'm aware of to disable power-saving features on the according phone:
Xiaomi Redmi Note 4 (Android 7): Works somewhat well, mostly gets called ~once an hour, sometimes gaps of 30mins to 4 hours.
Huawei P20 Pro (Android 10): Works the best so far, one or two missed calls per day, probably connectivity issues.
Samsung A6 2016 (LineageOS 17.1 Android 10): Called every one to 3 hours, but I suspect it's wifi issues; should probably log on the device to make sure.
Oppo A5 PBAM00 (Android 8.1): Worst offender so far, but it's running a Chinese ROM so not much of a surprise. Worker events are only delivered if I keep the app open in recent activities. They are then delivered every 60 to 90 minutes. If I don't switch to the app every couple days, the worker events eventually stop being delivered.

The first three seem like they might handle this concept quite well, I have the app running for a week now and the events keep coming in, even with the app "closed". The Oppo seems to be better suited for the current approach with a foreground service and perma-notification.

**Comment by bt90** [comment]
There's not much you can do to work around shitty vendor "powersaving" hacks. Some of them roll with a whitelist approach with a few blessed apps and kill everything else. But nice to see that the concept would probably work with phones from sane vendors.

**Comment by srett** [comment]
True. It's especially bad with Chinese ROMs as you basically only have like 4 apps in China that everyone needs, and the rest is crappy apps that you actually want treated that way as they would spam you with ad-notifications from the background, mine bitcoin, track you and whatnot otherwise. It makes sense to have a hard-coded whitelist. The Oppo for example by default also completely disables notifications for newly installed apps. Go figure why. What's unforgivable though is that there is absolutely no way to completely disable this power-saving crap for apps of your choice.

Anyways, what I was trying to say is that neither solution is a silver bullet, so it might indeed make sense to keep both ways of running Syncthing available, as @Catfriend1 pondered before, at least if you want to try and support those "special" phones.

**Comment by Catfriend1** [comment]
Do you know, how we can wrap the SyncthingNative executable into a forever-running WorkManager workload? From my reading, a "work" as defined by Android developer docs must end after some time, but may be allowed to run longer under special circumstances? E.g. see the download example in the docs. 

- https://developer.android.com/topic/libraries/architecture/workmanager
- https://www.reddit.com/r/androiddev/comments/e4nxjq/workmanger_android_duration_of_task_10_minutes/
-

**Comment by bt90** [comment]
I would prepare for the worst case scenario. Many vendors restrict any kind of background activity. Continuous execution of the native executable will be the exception to the rule.

So our "work" would be to run Syncthing for a variable amount of time and then shut it down properly. Either we introduce a setting for the time period or we calculate it based on previous runs.

**Comment by Catfriend1** [comment]
@bt90 This sounds like a good idea to do recurring one shot syncs... :-).

**Comment by Zulgrib** [comment]
Having multiple methods available would be great to ensure it works on most devices.
