### ISSUE TITLE
UX: Inconsistent icon colors

### ISSUE THREAD

**Issue by bt90** [Catfriend1/syncthing-android#839]
The icons are currently a mix of black and grey even if all menu items are enabled. It would be nice if we could switch all icons to black as this offers better contrast for both themes.

This is also a bit confusing as the grey items look like they are disabled.

![grafik](https://user-images.githubusercontent.com/1926175/130648536-4b3da0c8-c8c7-46c8-9d9b-515bfb4b95b6.png)

**Comment by Catfriend1** [comment]
@bt90 Yes, it would be a good idea. I'm not a good UX designer ;-). Somehow I've missed how to convert those assets to automatically the obey dark/light theme from Android. My hope relies on someone coming up who knows how to do this "xml instead of png" stuff so we don't need to care about every icon 18 times (grey, black, white - hdpi, xxhdpi, ... stuff). In my current situation, I didn't care as this is a time-waster for me. (Need to care about a young child)

**Comment by Catfriend1** [comment]
I've found out by accident that it requires the res/drawable/*.xml file to be added per asset to fix this. Android will then take care of the coloring itself (as the xml is not an image but some kind of metadata to draw the asset). I got a new asset from here recently: https://fonts.google.com/icons?selected=Material+Icons

So if someone reading this likes to help and look for the assets in *.xml file format, he/she's welcome :-).

**Comment by Catfriend1** [comment]
It's resolved in "main" now.

**Comment by Helium314** [comment]
@Catfriend1 this is great!
What did you use to convert the icons?

**Comment by Catfriend1** [comment]
@Helium314 I downloaded them from the Google Material Icons Library selecting "download for android black". It contained xml icon files.

**Comment by bt90** [comment]
Soooo much better now 🥳
