### ISSUE TITLE
Syncthing crashing on launch

### ISSUE THREAD

**Issue by fieldsmitchel** [Catfriend1/syncthing-android#857]
### Description of the issue
Syncthing crashing with exit code 141

### Reproduction Steps
Launch the app

### Version Information
- App Version: 1.18.3.0
- Syncthing Version: [blank]
- Android Version: Android 10
- Device manufacturer: Samsung
- Device model: SM-G965U
[19 13 22E yncth.txt](https://github.com/Catfriend1/syncthing-android/files/7449932/19.13.22E.yncth.txt)

**Comment by Catfriend1** [comment]
Hi,

this problem has been brought up before on the issue tracker - so this is a duplicate. Please search for "EROFS" (read only filesystem).

```
/storage/5268-CC51/Android/data/com.github.catfriend1.syncthingandroid/files/syncthing.log.tmp: open failed: EROFS (Read-only file system)
```

The ticket should go to the ROM vendor. Due to all files access it shouldn't be read only. Or it's one of those Android bugged devices where the storage partition for the primary storage is reported as SDcard incorrectly because that's secondary storage. Then it's an API problem in the vendor's ROM.

Regards.

**Comment by pipoprods** [comment]
Hi @Catfriend1 

I'm getting the same issue on my phone. The ROM I'm using is a community driven one I build myself. Given this I could investigate the issue better than users of commercial ROMs.

What would you like me to look at or test?

**Comment by Catfriend1** [comment]
@pipoprods We need to know why the getExternalDirectory Java API call returns the SDcard instead of internal storage (like on my test phones and emulator instances).

**Comment by pipoprods** [comment]
Hi @Catfriend1 after after some time leaving this "as-is" and a couple of reboots (maybe that's the point). I no more get the "EROFS" error… Everything's working like a charm.
Sorry I probably won't be of any help on this point :confused:
