### ISSUE TITLE
please explain : "Battery eater" problem is fixed.

### ISSUE THREAD

**Issue by eoli3n** [Catfriend1/syncthing-android#870]
How did this fork fix the problem ?

**Comment by Catfriend1** [comment]
it didn't - but at some point users reported the problem was no longer there. so some bug fix must have fixed this "aside" as well.

**Comment by Catfriend1** [comment]
The problem of battery eating is not easy to follow to one single root cause. Sometimes, users sync databases  (e.g. WhatsApp, GIT) or whole internal storage which may contain constantly changing .log files below /Android/.../app/....
Others had problems with their ROM staying awake with CPU etc. because the SyncthingNative "registers" for OS funca like Multicast for local discovery or file watches.
And the next user tells me the Android's builtin MediaScanner service which is triggered for incoming files (media, music,...) malfunctions in their rom and causes 100% cpu usage/hiccup because it attempted to scan a broken file ,(or: early scanned a file being transferred by SyncthingNative).
So many reasons... sorry, I can just say I'm lucky on my Android 12 Pixel Experience Rom because file access is fast (which wasn't on 11), battery usage is light and screen off +syncing in background works perfectly.
