### ISSUE TITLE
Document that persistent notification can be hidden in Android settings

### ISSUE THREAD

**Issue by e00E** [Catfriend1/syncthing-android#962]
The [wiki](https://github.com/Catfriend1/syncthing-android/wiki/Frequently-Asked-Questions#persistent-notification---required-or-optional) mentions that the persistent notification is required. Some users find it annoying to see the notification but don't care how this app manages to run in the background. For these users it is useful to know that they can hide the notification in their Android notification settings.

I'm making an issue for this because I don't know how to edit the wiki.

**Comment by Catfriend1** [comment]
Hi,

I thought - according to Android docs I've read years ago - the notification is required because Android calls this bundle of background activity tied to a notification "foreground service". If you got no notification, the OS might stop your app "when it thinks it's time to stop".

I've got other apps, like Telegram FOSS where the notification is also annoying, but they silently stop working in the background if I hide the notification via Android settings. That made me unsure, if we should advise users it would be okay doing so, because the next ticket would be "Syncthing unexepectedly stops in background, make it more stable".

**Comment by e00E** [comment]
In my experience hiding the notification has no side effects. The author of FairEmail says the same thing [here](https://github.com/M66B/FairEmail/blob/master/FAQ.md#user-content-faq2) . I trust his opinion a lot.

**Comment by Catfriend1** [comment]
Ok, then suggest an additional piece of text to add please. You can PR againt this file https://github.com/Catfriend1/syncthing-android/blob/main/wiki/Frequently-Asked-Questions.md
