### ISSUE TITLE
[Feature Request] Shizuku Root Support

### ISSUE THREAD

**Issue by xxxsskxxx** [Catfriend1/syncthing-android#978]
### Description of the Feature Request

I currently use this app with root to be able to backup / keep in sync my 'Download' folder on internal storgage to my TrueNAS, it is a massive help.

Im looking to come away from apps that require root, and ive managed to leverge DNS providers to cover adblock usage, and was now looking at alternatives to synchting (my goal is run root free via Magsk / Kernel / system changes)

I use Swift Backup to backup my apps and it achives root using Shizuku:-

https://github.com/RikkaApps/Shizuku

Is there a way the app could have this feature added to save unlocking bootloaders and using Magisk etc?

Thanks

**Comment by Catfriend1** [comment]
It might be possible on recent Android versions to select the Download path manually via web gui or the gear icon beside the folder path on the wrapper UI.

**Comment by SubZero5** [comment]
How can we use Shizuku with Syncthing-Fork?

**Comment by njdom24** [comment]
I think this could use some investigation. `Android/data` is not accessible by manually adding the path, at least on Android 14. ADB and (therefore) Shizuku allow this, so it would be helpful to have support for it as an `su`-lite option that works without root.

**Comment by JustVldKsh** [comment]
Bumping because it is not possible to sync (or normally even access without various workarounds or a desktop device) `Android/` folders on newer Android versions and Shizuku allows for on-device ADB access (without any other device needed from Android 11 onwards via wireless debugging) ~~and i am also unable to unlock my device at the moment (because manufacturer made the process lengthy and unnecessarily complicated for no reason) thus a huge Shizuku user~~

Also requesting to rename the issue to just `Shizuku Support` since Shizuku doesn't actually require root

My personal usecase would be to sync `/storage/emulated/0/Android/data/io.freetubeapp.freetube.nightly` (latest nightly of [MarmadileManteater/FreeTubeCordova](https://github.com/MarmadileManteater/FreeTubeCordova)) with the desktop and is currently the only issue that is holding me from using it instead of YT nowadays (gonna go create a )
Might also consider to sync/backup some other things like Mindustry saves or Telegram media too
