### ISSUE TITLE
Add information about the fork?

### ISSUE THREAD

**Issue by voidplayer** [Catfriend1/syncthing-android#99]
When forks happens theres a few reasons:
- upstream is dead
- upstream doesnt want my patches ( they disagree with them / they just hate me)
- upstream is slow  with patches

A few details about a fork
- This fork (doesnt) rebase frecuently with upstream
- upstream is slow but im not trying to get them upstream and they eventually all my patches

this are the biggest changes: (i think this is done already)

I know this is not how organically a fork is born, but when you search for syncthing in f-droid as an end user, you get 2 clients and you dont know which one to install

these bits of information would make a choice much easier for the end user

Thanks for considering!

**Comment by Catfriend1** [comment]
Hi the Problem why I'm not stating how to get in sync with the upstream again is I don't know if they agree with a) patches and b) development of enhancements or c) my strategy which lead to a lot of discussion in the past on the official repo. Currently, I'm waiting to see which patches they take from me which is perfectly ok for the official repos maintainer(s) to merge upstream from my side. A draft was already discussed some time ago before the fork began to draw a line between my work and aims and the aims official repos maintainer has. Then, a possible solution would have been that syncthing fork is a fast moving version of the app fixing and improving things, testing new features together while the official upstream app (in the near future?!) has a certain commitment to patches and audit first. The maintainer more than often stated in PR's that he'll rather likes to have a fully audited and as perfect and tight as possible solution (I'm just trying to find words for it in short form so please forgive me if not 100% accurate) or better have no PR unless many users experience a major problem with the app "as is". This lead to different strategies in both repos as my personal opinion is if you apply "never touch a running list thing" to software it will soon get more bugs due to OS and platform changes plus will outdate with old ways of doing its job.

**Comment by Catfriend1** [comment]
More discussion, info and "reasons" are here : https://forum.syncthing.net/t/folder-creation-broken-in-android-app/11885/2

**Comment by Catfriend1** [comment]
Related:
https://github.com/Catfriend1/syncthing-android/issues/48

I'll adjust the text of the fork explanation soon, just gimme a little bit of time... 🙂

**Comment by voidplayer** [comment]
Thanks for working on this!!

**Comment by Catfriend1** [comment]
Ok changing the readme here is not a big deal. I guess I need to file a PR on fdroid as they don't update the readme automatically according to GitHub.

**Comment by voidplayer** [comment]
Thanks!

Just think on the end user that faces two similar named syncthing clients and dont know which one to install...

Now that i know the story, i think i like yours much better! (never tried the original tho)

**Comment by Catfriend1** [comment]
Hi @voidplayer 
Could you please have a look at PR #120 and tell me if this fulfills your request in your eyes?

**Comment by voidplayer** [comment]
Commented on the pull

Thanks for improving this!!
